name: "✨ Feature"
description: "새로운 기능 추가 (제목은 'feat: Pub/Sub 기능 구현' 형태로 입력해 주세요)"
title: "feat "
labels: ["feat"]
body:
  - type: textarea
    attributes:
      label: 📄 설명
      description: |
        새로운 기능에 대한 설명을 작성해 주세요.
        예: 클라이언트가 PUBLISH, SUBSCRIBE 명령을 통해 메시징 기능을 이용할 수 있도록 구현
        예: SAVE 명령을 추가하여 현재 캐시 상태를 파일로 즉시 저장하도록 구현
    validations:
      required: true
  - type: textarea
    attributes:
      label: ✅ 작업할 내용
      description: |
        할 일을 체크박스 형태로 작성해주세요.
        예:
        - [ ] CommandParser에 PUBLISH/SUBSCRIBE 명령 파싱 로직 추가
        - [ ] PubSubManager 클래스 설계 및 메시지 큐 구현
        - [ ] SnapshotManager에 SAVE/PERSIST 명령어 처리 로직 구현
    validations:
      required: true
  - type: textarea
    attributes:
      label: 💡 참고 자료
      description: |
        참고 자료가 있다면 작성해 주세요.
        예:
        - Redis Pub/Sub 공식 문서
        - 구현할 기능의 상세 프로토콜 명세
        참고 자료가 없는 경우 `_No response_`로 작성해 주세요.